### ISSUE TITLE
Visualize periods of movement

### ISSUE THREAD

**Issue by PCdLf** [PCdLf/e4dashboard#15]
8.	Viz Tab : Beweging: Kunnen we in de grafiek weergeven dat er sprake is van veel beweging. 
9.	Vraag was ook vaak: Hier is een piek, wat gebeurde hier. Vandaar de koppeling met de agenda. En soms moesten we mensen erop wijzen dat er ook een piek in beweging is, dus de verklaring wss sporten. Daar willen we idealiter ook automatisch iets voor. Dus dat interessante pieken ge-highlight worden (automatisch), en pieken door bv beweging niet (die springen vaak erg in het oog omdat ze heel hoog zijn).

**Comment by SJKOL** [comment]
Idea is to add 2 plots to the downloadable report:
- a bar colorcoding how much movement there is
- a bar colorcoding how much noise the EDA signal has
Both give the researcher an indication of how trutworthy data in a particular period is.

**Comment by PCdLf** [comment]
Added the ability to change the y-axis of the move scale, to visualize movement
